//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bankomat
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BankomatV2Entities : DbContext
    {
        public BankomatV2Entities()
            : base("name=BankomatV2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Banche> Banche { get; set; }
        public virtual DbSet<Clienti> Clienti { get; set; }
        public virtual DbSet<ContiCorrente> ContiCorrente { get; set; }
        public virtual DbSet<Funzioni> Funzioni { get; set; }
        public virtual DbSet<Movimenti> Movimenti { get; set; }
    }
}
